#ifndef DEF_SETTINGS_H
#define DEF_SETTINGS_H

#include <QSettings>

#define SETTINGS_1_MENU 1
#define SETTINGS_1_CASH_DATE_CHANGE 2
#define SETTINGS_1_HALL 3
#define SETTINGS_1_CASH_PRINTER 4
#define SETTINGS_1_DB 5
#define SETTINGS_1_AVAILABLE_HALLS 6
#define SETTINGS_1_UPDATE_DATETIME 7

#define SETTINGS QSettings s("Jazzve", "Cafe4");

#endif // DEF_SETTINGS_H
