#ifndef DEFINITIONS_H
#define DEFINITIONS_H

#define MOVEMENT_RESULT_OK 0
#define MOVEMENT_RESULT_SRC_TABLE_NOT_DEFINED 1
#define MOVEMENT_RESULT_DST_TABLE_NOT_DEFINED 2
#define MOVEMENT_RESULT_CANNOT_LOCK_TABLE 3
#define MOVEMENT_RESULT_NETWORK_ERROR 4

#define PAYMENT_COUNTED 1
#define PAYMENT_SERVICE 2
#define PAYMENT_DISCOUNT 3
#define PAYMENT_TOTAL 4

#define APP_FONT_NAME "Arial LatArm Unicode"

#define CODE_PRINT_CHECK_NAME_NOT_DEFINED 27

#endif // DEFINITIONS_H
